### ISSUE TITLE
Weekly Sync Call 08.06.2020

### ISSUE THREAD

**Issue by ligi** [sourcifyeth/org#1]
Topics:
 * proposed by @franzihei: defining what should be communicated / shared with our twitter account
 * final decision on directory structure: https://github.com/ethereum/sourcify/issues/181
 * check if the Manifest is there as @edisinovcic promised https://github.com/ethereum/sourcify/issues/159
 * do we want to use this github org or continue to have everything in the ethereum org
 * alternatives to circleCI
 * email address info@sourcify.dev or sourcify@sourcify.dev or sourcify@ethereum.org

**Comment by franzihei** [comment]
+ Next steps with the `sourcify.dev` and `sourcify.eth `domains!

**Comment by edisinovcic** [comment]
Discuss UI design proposal on: https://www.figma.com/file/N59JoAXcaAZVHPXG1ayEfg/sourcify

**Comment by edisinovcic** [comment]
daapp node implementation
