### ISSUE TITLE
Weekly Sync 17.08.2020

### ISSUE THREAD

**Issue by franzihei** [sourcifyeth/org#12]
## Topics for our weekly catch-up

1. Dappnode deployment - Ligi are guys from dappnode joining? (we can do this first) 
2. Development update
3. Value proposition canvas and discussion on that part @franzihei --> https://docs.google.com/presentation/d/19kuVAqMkl33W4do-J-eLvybmP0zHBU--lBxcnP2dlVk/edit?usp=sharing

**Comment by edisinovcic** [comment]
Link for [monitoring logs ](http://164.90.219.76:11000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22loki%22,%7B%22expr%22:%22%7Bcompose_project%3D%5C%22environments%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
Onboarding interviews? @franzihei

**Comment by DeFiYaco** [comment]
Development update:
Merged dappnode support, docker images optimized and monitoring for services into master
https://github.com/ethereum/sourcify/pull/243
Project rewrite in progress and verification queue:
https://github.com/ethereum/sourcify/pull/224

**Comment by franzihei** [comment]
- Truffle plugin (direct support for verification via Truffle)
- Brownie support too?

**Comment by franzihei** [comment]
- Wallet plugins? (MM, Wallet Connect?)

**Comment by edisinovcic** [comment]
Priorities:
* add support for truffle .json file (searching for metadata inside that file)
* add support for .zip files that contain multiple source and metadata files
* make chain and address optional
* add support for sourcify-cli to upload sources and metadata files to server
