### ISSUE TITLE
weekly sync 28.09.2020

### ISSUE THREAD

**Issue by ligi** [sourcifyeth/org#14]
* state of IPFS publishing
* IPFS 0.7 (key migration)

**Comment by DeFiYaco** [comment]
- services progress

**Comment by edisinovcic** [comment]
Update validation to have nicely formated json as a response.
For truffle projects scan all the files and try to figure out if they are json (start with '{' etc.). For metadata try to find if it contains '{compiler' etc.
Merge ipfs to master from staging.
