### ISSUE TITLE
sync 7.12.2020.

### ISSUE THREAD

**Issue by DeFiYaco** [sourcifyeth/org#25]
- discuss the best approach for storing keccak and bytecode

**Comment by edisinovcic** [comment]
* Hardware requirements to run geth fork
* Gnosis wallet integration -> possible call with gnosis team?
* Tenderly report
* Sourcify as a vscode plugin (through Remix -> possible integration to all tools that use vscode)

**Comment by FabijanC** [comment]
- Monitor rewrite
