### ISSUE TITLE
Sourcify FAQ Post

### ISSUE THREAD

**Issue by franzihei** [sourcifyeth/org#3]
Hey guys, I created an FAQ and filled in the answers here: 
https://hackmd.io/@franzihei/rJDae123U

Can you please review and see my comments. Maybe @edisinovcic can you have a look if you have some minutes? Then I can bring it into a final shape once I have the missing inputs. 

Thank you!

**Comment by edisinovcic** [comment]
I left a couple of comments. @chriseth can you take a look here: https://hackmd.io/czgRFHgCR-yldOA0tLuW7w?both#How-can-you-retrieve-the-metadata

And write in short what tools did you use on extracting metadata from them so I can create a short tutorial/description of that so users can get proper metadata from those tools.

**Comment by franzihei** [comment]
done and published here https://solidity.ethereum.org/2020/06/25/sourcify-faq/
