### ISSUE TITLE
sync 30.08.21

### ISSUE THREAD

**Issue by franzihei** [sourcifyeth/org#64]
## Topics from last week:
- apply for filecoin-plus https://docs.filecoin.io/store/filecoin-plus/ (also maybe add filecoin to supported chains?)
- filename char substitution problem: https://twitter.com/alexberegszaszi/status/1428711708055461890 / should we change it or give headsup to people to not use the sources?

## New topics:
- close down Discord server before it's too late and move to Matrix spaces?
- all ready for the handover?
-  prepared a general onboarding doc: https://docs.google.com/document/d/1ZemcLmjq162lgjSqexkWpKZDepgieemyCM30Fu2hEaI/edit?usp=sharing

**Comment by ligi** [comment]
* downtime mitigation due to office move
 * time for call with new coders on wednesday
 * moving meet to meet.ethereum.org

**Comment by FabijanC** [comment]
- Architecture doc PR: https://github.com/ethereum/sourcify/pull/503
- Monitor: temporary fix to use an available node
- New production version
