### ISSUE TITLE
Weekly sync 13.07.2020

### ISSUE THREAD

**Issue by edisinovcic** [sourcifyeth/org#9]
Done:
* UI merged (https://github.com/ethereum/sourcify/pull/210)
* Directory structure merged (todo: script for rewriting old fomart to new, currently both are mixed on staging branch)
* Sourcify cli (working, publish to npm via ci todo)

Next:
* New metadata format for solidity 0.7 (ethereum/sourcify#202)
* Explanations on how to extract metadata from truffle and Remix (https://github.com/ethereum/sourcify/issues/206)

**Comment by edisinovcic** [comment]
Rename source-verify to sourcify in readme. Add link to https://github.com/sourcifyeth.
Add gitter icon to the UI.

**Comment by franzihei** [comment]
I can also help with making the Readmes nicer. :)

**Comment by franzihei** [comment]
Make little screen recording and step-by-step explanation for metadata extraction:
- Truffle
- Remix
- Manually?
